Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -95,4 +95,94 @@ echo "$(date)creating virtual port"
 viripprt=$(openstack port create --network "$def_network" --fixed-ip subnet="$def_subnet" --no-security-group "$virtualip" )
 
 ipadd_notassign=$(openstack floating ip list --status DOWN -f value -c "Floating IP Address")
+# servers deployment bastion
+serv_contained=$(openstack server list --status ACTIVE --column Name -f value)
+
+if ! echo "$serv_contained" | grep -q "$bastionserv"; then
+    if [[ -n "$ipadd_notassign" ]]; then
+        floating_ip1=$(echo "$ipadd_notassign" | awk '{print $1}')
+        if [[ -n "$floating_ip1" ]]; then
+            echo "$(date) floating IP is given for bastion server"
+        else
+            echo "$(date) Creating floating IP for bastion"
+            floating_ip1create=$(openstack floating ip create ext-net -f json | jq -r '.floating_ip_address' > floatipadd1)
+            floating_ip1="$(cat floatipadd1)"
+        fi
+    else
+            echo "$(date) Creating floating IP for bastion"
+            floating_ip1create=$(openstack floating ip create ext-net -f json | jq -r '.floating_ip_address' > floatipadd1)
+            floating_ip1="$(cat floatipadd1)"
+    fi
+
+    create_bastion=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $bastionserv --key-name $def_keypair --flavor "1C-2GB-50GB" --network $def_network --security-group $def_security_grp)
+    fipadd_bastion=$(openstack server add floating ip $bastionserv $floating_ip1)
+    echo "$(date) Created $bastionserv server"
+else
+    echo "$(date) $bastionserv already exists"
+fi
+#servers deployment haproxies
+if ! echo "$serv_contained" | grep -q "$haproxyserv"; then
+    if [[ -n "$ipadd_notassign" ]]; then
+        floating_ip2=$(echo "$ipadd_notassign" | awk '{print $2}')
+        if [[ -n "$floating_ip2" ]]; then
+            echo "$(date) floating IP is given for Haproxy server"
+        else
+            echo "$(date) Creating floating IP for Haproxy"
+            floating_ip2create=$(openstack floating ip create ext-net -f json | jq -r '.floating_ip_address' > floatipadd2)
+            floating_ip2="$(cat floatipadd2)"
+        fi
+    else
+            echo "$(date) Creating floating IP for Haproxy"
+            floating_ip2create=$(openstack floating ip create ext-net -f json | jq -r '.floating_ip_address' > floatipadd2)
+            floating_ip2="$(cat floatipadd2)"
+    fi
+
+    create_haproxy=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $haproxyserv --key-name $def_keypair --flavor "1C-2GB-50GB" --network $def_network --security-group $def_security_grp)
+    create_haproxy2=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" $haproxyserv2 --key-name $def_keypair --flavor "1C-2GB-50GB" --network $def_network --security-group $def_security_grp) 
+    echo "$(date) two haproxy $haproxyserv and $haproxyserv2 servers are created"
+else
+    echo "$(date) two haproxy $haproxyserv and $haproxyserv2 servers already exists"
+fi
+
+vip_fipadding=$(openstack floating ip set --port "$virtualip" $floating_ip2)
+addrof_virip=$(openstack port show "$virtualip" -f value -c fixed_ips | grep -Po '\d+\.\d+\.\d+\.\d+')
+echo "$addrof_virip" >> addr_vip
+
+prtupdte=$(openstack port set --allowed-address ip-address="$floating_ip2" "$virtualip")
+
+number_devlopserv=$(grep -ocP "$devlop_serv" <<< "$serv_contained")
+
+if ((no_of_serv < number_devlopserv)); then
+    devlopserv_takeout=$((number_devlopserv - no_of_serv))
+    for ((i = 0; i < devlopserv_takeout; i++)); do
+        devserv_remove=$(openstack server list --status ACTIVE -f value -c Name | grep -m1 -oP "${tag}"'_dev([1-9]+)')
+        removed_serv=$(openstack server delete "$devserv_remove" --wait)
+        echo "$(date) Deleted $devserv_remove"
+    done
+elif ((no_of_serv > number_devlopserv)); then
+    devlopserv_plus=$((no_of_serv - number_devlopserv))
+    j=$((number_devlopserv + 1))
+
+    for ((i = 0; i < devlopserv_plus; i++)); do
+        namedevlopserver="${devlop_serv}${j}"
+        dser_create=$(openstack server create --image "Ubuntu 20.04 Focal Fossa x86_64" "$namedevlopserver" --key-name "$def_keypair" --flavor "1C-2GB-50GB" --network "$def_network" --security-group "$def_security_grp")
+        echo "$(date) Created $namedevlopserver server"
+
+        active=false
+        until $active; do
+            server_status=$(openstack server show "$namedevlopserver" -f value -c status)
+            if [[ "$server_status" == "ACTIVE" ]]; then
+                active=true
+            fi
+        done
+
+        ((j++))
+    done 
+else
+    echo "Required number of dev servers "$no_of_serv" already exists"
+fi
+floataddr_bastion=$(openstack server list --name $bastionserv -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
+floataddr_proxy1=$(openstack server show $haproxyserv -c addresses | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
+floataddr_proxy2=$(openstack server list --name $haproxyserv2 -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
+
 
